---
- name: Create a docker ansible lab or other ssh based lab environment
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  roles:
    - create-docker-networks
    - create-docker-instances
    - create-inventory
    - create-lab-directory
...
