---
- name: create a docker three tier app environment
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    docker_network: three-tier-tier-network
    docker_subnet: '172.3.26.0/16'
    docker_image: jdeathe/centos-ssh:centos-7
    lab_machines:
      - { name: bastion,    ip: 172.3.26.1, port_maps: "2222:22", group: bastions }
      - { name: frontend1,  ip: 172.3.26.3, port_maps: "2223:22", group: frontends }
      - { name: app1,       ip: 172.3.26.4, port_maps: "2224:22", group: apps }
      - { name: app2,       ip: 172.3.26.5, port_maps: "2225:22", group: apps }
      - { name: appdb1,     ip: 172.3.26.6, port_maps: "2226:22", group: appdbs }

  tasks:

  - name: create a {{ docker_network }} with options
    docker_network:
      name: "{{ docker_network }}"
      driver_options:
        com.docker.network.bridge.name: 3tier
      ipam_options:
        subnet: '172.3.26.0/16'
        gateway: 172.3.26.1

  - name: create lab hosts 
    docker_container:
      name: "{{ item.name }}"
      image: "{{ docker_image }}"
      ports:
             - "{{ item.port_maps }}"
      networks:
        - name: "{{ docker_network }}"
          ipv4_address: "{{ item.ip }}"
      env:
        SSH_SUDO: ALL=(ALL) NOPASSWD:ALL
        SSH_USER: vagrant
    with_items: "{{ lab_machines }}"

        -  
