---
- name: Create the individual lab hosts 
  docker_container:
    name: "{{ item.name }}"
    image: "{{ docker_image }}"
    privileged: yes
    ports:
      "{{ item.port_maps }}"
    networks:
      - name: "{{ docker_network }}"
        ipv4_address: "{{ item.ip }}"
    env:
      SSH_SUDO: ALL=(ALL) NOPASSWD:ALL
      SSH_USER: vagrant
  loop: "{{ lab_machines }}"
...
