---
- name: create a docker ansible or other ssh based environment
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    docker_network:   three_tier_network

  tasks:

  - name: create a {{ docker_network }} with options
    docker_network:
      name: "{{ docker_network }}"
      driver_options:
        com.docker.network.bridge.name: 3tier
      ipam_options:
        subnet: '172.3.26.0/16'
        gateway: 172.3.26.1

  - name: create lab hosts 
    docker_container:
      name: "{{ item.name }}"
      image: "{{ docker_image }}"
      ports:
        "{{ item.port_maps }}"
      networks:
        - name: "{{ docker_network }}"
          ipv4_address: "{{ item.ip }}"
      env:
        SSH_SUDO: ALL=(ALL) NOPASSWD:ALL
        SSH_USER: vagrant
    with_items: "{{ lab_machines }}"

  - name: create in-memory inventory
    add_host:
      name: "{{ item.name }}"
      groups: "{{ item.group}}"
    with_items: "{{ lab_machines }}"

- name: smoke test lab
  hosts: all
  gather_facts: false

  tasks:
    
  - name: ping lab hosts
    ping:

    #
    #          - name: create file
    #            become: yes
    #            template:
    #                src: ansible-hosts.j2
    #                  dest: "{{ wm_inventory_file }}"  
