---
- name: Create lab directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ lab_directory }}" 
    - "{{ lab_directory }}/ssh" 
    - "{{ lab_directory }}/utilities" 

- name: Generate lab static inventory file
  template:
    src: templates/lab_inventory.j2
    dest: "{{ lab_directory }}/hosts"

- name: Copy vagrant key to lab/ssh
  fetch:
    src: ./ssh/vagrant.private
    dest: "{{ lab_directory }}/ssh/vagrant.private"
    flat: true

- name: Set vagrant insecure ssh key permissions
  file: 
    path: "{{ lab_directory }}/ssh/vagrant.private"
    mode: 0400

- name: Write ansible lab config files
  template:
    src: "templates/{{ item.file }}.j2"
    dest: "{{ lab_directory }}/{{ item.directory }}/{{ item.file }}"
  loop: "{{ lab_files }}"

